name: Deploy to Heroku
on:
  push:
    branches:
      - main
    paths:
    - 'api/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: cd api && npm ci
    - name: Build
      run: cd api && npm run build
    - name: Deploy to Heroku
      run: |
        # Navigate to the directory to deploy
        cp package.json api/dist/package.json
        cd api/dist
    
        # Initialize a new Git repository and add all files
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git init
        git add .
    
        # Commit the files
        git commit -m "Deploy"
    
        # Push the commit to a new branch in the same repository
        git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" HEAD:api-live -f
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}