name: Deploy to Heroku
on:
  push:
    branches:
      - main
    paths:
    - 'api/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: cd api && npm ci
    - name: Build
      run: cd api && npm run build
    - name: Deploy to Heroku
      run: |
        # Install Heroku CLI
        curl https://cli-assets.heroku.com/install.sh | sh
    
        # Authenticate with Heroku CLI
        heroku auth:token ${{ secrets.HEROKU_API_KEY }}
    
        # Navigate to the directory to deploy
        cd api/dist
    
        # Initialize a new Git repository
        git init
    
        # Add all files to the Git repository
        git add .
    
        # Commit the files
        git commit -m "Deploy"
    
        # Add the Heroku app as a remote
        git remote add heroku https://git.heroku.com/rate-my-everything.git
    
        # Push the commit to Heroku
        git push -f heroku master
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}